name: Executar GM Search Crawler

on:
  workflow_dispatch:
    inputs:
      termo:
        description: 'Digite o termo para buscar na biblioteca DuckDuckGo'
        required: true
        default: 'Automação'

jobs:
  run-library-search:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Baixar o codigo do seu repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Biblioteca DuckDuckGo Search
      run: |
        pip install requests duckduckgo-search

    - name: Executar Busca na Web Sob Demanda
      run: |
        python "list/GM Search/crawler.py" "${{ github.event.inputs.termo }}"

    - name: Publicar Banco de Dados Atualizado no Pages
      run: |
        git config --global user.name 'GM Backend Bot'
        git config --global user.email 'bot@gmcorporation.com.br'
        git checkout main
        git add "list/GM Search/index_cache.json"
        
        if ! git diff --quiet --cached; then
          git commit -m "⚙️ [GM Search] Banco de dados atualizado com a biblioteca para '${{ github.event.inputs.termo }}'"
          git pull --rebase origin main
          git push origin main
        fi
